# Generated by Django 5.2.4 on 2025-07-21 21:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField()),
                ('is_root', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='my_auth.profile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cdn.folder')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('file_extension', models.CharField(blank=True, max_length=20)),
                ('storage_path', models.TextField()),
                ('storage_bucket', models.CharField(blank=True, max_length=255)),
                ('md5_hash', models.CharField(blank=True, db_index=True, max_length=32)),
                ('sha256_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('cdn_url', models.URLField(blank=True, null=True)),
                ('cdn_edge_locations', models.JSONField(blank=True, default=list)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('upload_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='my_auth.profile')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cdn.folder')),
            ],
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('storage_path', models.TextField()),
                ('file_size', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_auth.profile')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cdn.file')),
            ],
            options={
                'indexes': [models.Index(fields=['file'], name='cdn_filever_file_id_6c1d10_idx'), models.Index(fields=['created_at'], name='cdn_filever_created_6f5242_idx')],
                'unique_together': {('file', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner', 'path'], name='cdn_folder_owner_i_e1d5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['parent'], name='cdn_folder_parent__947483_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner', 'created_at'], name='cdn_folder_owner_i_7f4b31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('owner', 'parent', 'name')},
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner'], name='cdn_file_owner_i_563ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['folder'], name='cdn_file_folder__1da0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['md5_hash', 'sha256_hash'], name='cdn_file_md5_has_c6dd51_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['mime_type'], name='cdn_file_mime_ty_0ddeb8_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_size'], name='cdn_file_file_si_cded7c_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner', 'created_at'], name='cdn_file_owner_i_d2f43a_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['processing_status'], name='cdn_file_process_88ea09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('owner', 'folder', 'filename')},
        ),
    ]
