# Generated by Django 5.2.4 on 2025-07-21 22:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0001_initial'),
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('file', 'File'), ('folder', 'Folder')], max_length=10)),
                ('resource_id', models.UUIDField()),
                ('permission_level', models.CharField(choices=[('view', 'View Only'), ('download', 'Download'), ('edit', 'Edit'), ('admin', 'Admin')], default='view', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('public_token', models.CharField(blank=True, max_length=255, unique=True)),
                ('password_protected', models.BooleanField(default=False)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('allow_download', models.BooleanField(default=True)),
                ('allow_preview', models.BooleanField(default=True)),
                ('download_limit', models.IntegerField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_shares', to='my_auth.profile')),
                ('shared_with_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to='my_auth.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ShareAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_type', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('preview', 'Preview')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_auth.profile')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='cdn.share')),
            ],
        ),
        migrations.CreateModel(
            name='StarredItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('file', 'File'), ('folder', 'Folder')], max_length=10)),
                ('resource_id', models.UUIDField()),
                ('starred_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_items', to='my_auth.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TrashItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('file', 'File'), ('folder', 'Folder')], max_length=10)),
                ('resource_id', models.UUIDField()),
                ('original_name', models.CharField(max_length=255)),
                ('original_path', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('permanent_delete_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trash_items', to='my_auth.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('view', 'View'), ('share', 'Share'), ('delete', 'Delete'), ('restore', 'Restore'), ('move', 'Move'), ('rename', 'Rename'), ('copy', 'Copy')], max_length=50)),
                ('resource_type', models.CharField(blank=True, choices=[('file', 'File'), ('folder', 'Folder')], max_length=10, null=True)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('resource_name', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='my_auth.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='cdn_activit_user_id_c85547_idx'), models.Index(fields=['action_type'], name='cdn_activit_action__22d46e_idx'), models.Index(fields=['resource_type', 'resource_id'], name='cdn_activit_resourc_44ac73_idx'), models.Index(fields=['created_at'], name='cdn_activit_created_b7a75a_idx')],
            },
        ),
        migrations.CreateModel(
            name='FileAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_date', models.DateField()),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('avg_response_time', models.IntegerField(blank=True, null=True)),
                ('cache_hit_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('referrer_domain', models.CharField(blank=True, max_length=255)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='cdn.file')),
            ],
            options={
                'db_table': 'cdn_file_analytics',
                'indexes': [models.Index(fields=['file', 'access_date'], name='cdn_file_an_file_id_814949_idx'), models.Index(fields=['access_date'], name='cdn_file_an_access__6ee650_idx'), models.Index(fields=['country_code'], name='cdn_file_an_country_21e151_idx')],
                'unique_together': {('file', 'access_date', 'country_code')},
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('thumbnail', 'Generate Thumbnail'), ('preview', 'Generate Preview'), ('virus_scan', 'Virus Scan'), ('metadata_extract', 'Extract Metadata'), ('compress', 'Compress File')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=5)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('error_message', models.TextField(blank=True)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='cdn.file')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='cdn_process_status_adb762_idx'), models.Index(fields=['file'], name='cdn_process_file_id_a7498f_idx'), models.Index(fields=['job_type'], name='cdn_process_job_typ_82f556_idx'), models.Index(fields=['priority', 'created_at'], name='cdn_process_priorit_3cfa26_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['resource_type', 'resource_id'], name='cdn_share_resourc_076f56_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['owner'], name='cdn_share_owner_i_c86261_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['shared_with_user'], name='cdn_share_shared__eab17f_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['public_token'], name='cdn_share_public__9807cf_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['is_public', 'expires_at'], name='cdn_share_is_publ_c30004_idx'),
        ),
        migrations.AddIndex(
            model_name='shareaccesslog',
            index=models.Index(fields=['share'], name='cdn_shareac_share_i_de1ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='shareaccesslog',
            index=models.Index(fields=['accessed_at'], name='cdn_shareac_accesse_da237d_idx'),
        ),
        migrations.AddIndex(
            model_name='shareaccesslog',
            index=models.Index(fields=['access_type'], name='cdn_shareac_access__a0379e_idx'),
        ),
        migrations.AddIndex(
            model_name='starreditem',
            index=models.Index(fields=['user'], name='cdn_starred_user_id_a442e6_idx'),
        ),
        migrations.AddIndex(
            model_name='starreditem',
            index=models.Index(fields=['starred_at'], name='cdn_starred_starred_a40867_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='starreditem',
            unique_together={('user', 'resource_type', 'resource_id')},
        ),
        migrations.AddIndex(
            model_name='trashitem',
            index=models.Index(fields=['user'], name='cdn_trashit_user_id_4b078e_idx'),
        ),
        migrations.AddIndex(
            model_name='trashitem',
            index=models.Index(fields=['permanent_delete_at'], name='cdn_trashit_permane_726e63_idx'),
        ),
        migrations.AddIndex(
            model_name='trashitem',
            index=models.Index(fields=['deleted_at'], name='cdn_trashit_deleted_4d6851_idx'),
        ),
    ]
