# Generated by Django 5.2.4 on 2025-07-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0002_share_shareaccesslog_starreditem_trashitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashitem',
            name='cdn_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
