# Generated by Django 5.2.4 on 2025-07-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0003_trashitem_cdn_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
