# Generated by Django 5.2.4 on 2025-07-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0004_file_is_trashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
