# Generated by Django 5.2.4 on 2025-07-24 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0005_folder_is_trashed'),
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('view', 'View Only'), ('download', 'Download'), ('edit', 'Edit'), ('admin', 'Admin')], default='view', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='share',
            name='cdn_share_shared__eab17f_idx',
        ),
        migrations.RemoveField(
            model_name='share',
            name='shared_with_user',
        ),
        migrations.AddField(
            model_name='shareduserpermission',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdn.share'),
        ),
        migrations.AddField(
            model_name='shareduserpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_auth.profile'),
        ),
        migrations.AddField(
            model_name='share',
            name='shared_with',
            field=models.ManyToManyField(related_name='received_shared_resources', through='cdn.SharedUserPermission', to='my_auth.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='shareduserpermission',
            unique_together={('share', 'user')},
        ),
    ]
