# Generated by Django 5.2.4 on 2025-07-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0006_shareduserpermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='public_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
